name: Foundation feature branch workflow

on:
  push:
    branches:
      - 'feature**'

jobs:

  terraform-ci:
    # uses: itau-corp/itau-jb7-infra-foundation-azure/.github/workflows/ci.yml@develop
    uses: ./.github/workflows/ci.yml
    with:
      environment: dev
    secrets: inherit